export {default as Button1_1} from '../components/buttons/Button1_1.vue';
export {default as Button1_2} from '../components/buttons/Button1_2.vue';
export {default as Button2} from '../components/buttons/Button2.vue';
export {default as Button3} from '../components/buttons/Button3.vue';
export {default as Button4} from '../components/buttons/Button4.vue';
export {default as Dialog1} from '../components/dialogs/Dialog1.vue';
export {default as Form1} from '../components/forms/Form1.vue';
export {default as Switch1} from '../components/switches/Switch1.vue';
export {default as Tabs1} from '../components/tabs/Tabs1.vue';
